# Generated by Django 2.2.16 on 2023-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Введите текст комментария',
                                   max_length=200,
                                   verbose_name='Текст комментария'),
        ),
    ]
