# Generated by Django 2.2.16 on 2023-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0008_auto_20230311_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Введите текст комментария',
                                   verbose_name='Текст комментария'),
        ),
    ]
